apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend-app
    component: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: frontend-app
    component: frontend
