apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-volume
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/data/db'
